version: '3'

services:

  pecha-ai:
    container_name: pecha-ai
    build: ./
    restart: always
    volumes:
      - ./config.json:/app/config.json
      - ./:/app/
    ports:
      - 8080:8080
